// Generated by uniffi-bindgen-react-native
#include "react-native-rustok-bridge.h"
#include "generated/rustok_mobile_bindings.hpp"

namespace rustokbridge {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeRustokMobileBindings::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}